import * as T from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';

const host=document.getElementById('stage'), push=document.getElementById('push'), status=document.getElementById('status');
const scene=new T.Scene(); scene.background=new T.Color(0xffffff);
const camera=new T.PerspectiveCamera(34,1,.1,100);
camera.position.set(7.6,8.5,10.5); camera.lookAt(0,-.05,0);
const r=new T.WebGLRenderer({antialias:true}); r.setPixelRatio(Math.min(2,devicePixelRatio||1)); r.shadowMap.enabled=true; host.appendChild(r.domElement);
scene.add(new T.HemisphereLight(0xffffff,0x888888,2.8));
const dl=new T.DirectionalLight(0xffffff,3.8); dl.position.set(-5,10,6); dl.castShadow=true; scene.add(dl);
const ground=new T.Mesh(new T.PlaneGeometry(30,30),new T.ShadowMaterial({opacity:.12})); ground.rotation.x=-Math.PI/2; ground.position.y=-1.19; ground.receiveShadow=true; scene.add(ground);
const sm=(c,m=.25,q=.35)=>new T.MeshStandardMaterial({color:c,metalness:m,roughness:q});
function mesh(g,m,y){const x=new T.Mesh(g,m);x.position.y=y;x.castShadow=x.receiveShadow=true;scene.add(x);return x}
mesh(new T.CylinderGeometry(4.5,4.8,1.15,64),sm(0xd85b61,.28,.3),-.6);
mesh(new T.CylinderGeometry(4.78,4.72,.18,64),sm(0xb94450,.24,.34),-1.12);
mesh(new T.CylinderGeometry(4.05,4.05,.13,64),sm(0xc8d82e,0,.9),.01);
const ring=mesh(new T.TorusGeometry(4.12,.14,16,72),sm(0x27a8c6,.32,.27),.08); ring.rotation.x=Math.PI/2;
const dome=mesh(new T.SphereGeometry(4.15,64,32,0,Math.PI*2,0,Math.PI/2),new T.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.14,roughness:.025,transmission:.38,thickness:.1,ior:1.45,side:T.DoubleSide,depthWrite:false}),.08);
const dm=new T.MeshPhysicalMaterial({color:0xeadbb9,roughness:.34,clearcoat:.28,clearcoatRoughness:.3});
const spots={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[1,-1],[-1,1],[1,1]],5:[[-1,-1],[1,-1],[0,0],[-1,1],[1,1]],6:[[-1,-1],[1,-1],[-1,0],[1,0],[-1,1],[1,1]]};
const faces=[[0,1,0,1],[0,-1,0,6],[1,0,0,3],[-1,0,0,4],[0,0,1,5],[0,0,-1,2]],Z=new T.Vector3(0,0,1);
function roundedBox(size=1.02,radius=.14,segments=6){const g=new T.BoxGeometry(size,size,size,segments,segments,segments),p=g.attributes.position,half=size/2,inner=half-radius,v=new T.Vector3(),q=new T.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i);q.set(T.MathUtils.clamp(v.x,-inner,inner),T.MathUtils.clamp(v.y,-inner,inner),T.MathUtils.clamp(v.z,-inner,inner));v.sub(q).normalize().multiplyScalar(radius).add(q);p.setXYZ(i,v.x,v.y,v.z)}p.needsUpdate=true;g.computeVertexNormals();return g}
function die(x){const g=new T.Group(),cube=new T.Mesh(roundedBox(),dm);cube.castShadow=true;g.add(cube);for(const [nx,ny,nz,num] of faces){const n=new T.Vector3(nx,ny,nz),up=Math.abs(n.y)>.5?new T.Vector3(0,0,-1):new T.Vector3(0,1,0),right=new T.Vector3().crossVectors(up,n).normalize(),vert=new T.Vector3().crossVectors(n,right).normalize();for(const [a,b] of spots[num]){const sh=new T.Mesh(new T.CircleGeometry(.093,18),new T.MeshBasicMaterial({color:0x5a3925,transparent:true,opacity:.38,side:T.DoubleSide}));sh.position.copy(n).multiplyScalar(.516).addScaledVector(right,a*.205).addScaledVector(vert,b*.205);sh.quaternion.setFromUnitVectors(Z,n);g.add(sh);const p=new T.Mesh(new T.CircleGeometry(.071,18),new T.MeshBasicMaterial({color:0x4a2b1b,side:T.DoubleSide}));p.position.copy(n).multiplyScalar(.518).addScaledVector(right,a*.205).addScaledVector(vert,b*.205);p.quaternion.setFromUnitVectors(Z,n);g.add(p)}}g.scale.setScalar(1.15);g.position.set(x,1.3,0);scene.add(g);return{m:g,v:new T.Vector3(),w:new T.Vector3(),t:0,rest:false}}
const dice=[die(-.65),die(.65)],F=.69,R=3.34; let rolling=false,last=performance.now(),audio;
function reset(d,i){d.rest=false;d.t=0;d.m.position.set(i?.65:-.65,1.25+Math.random()*.3,(Math.random()-.5)*.6);d.m.rotation.set(Math.random()*6,Math.random()*6,Math.random()*6);d.v.set((Math.random()-.5)*5.3,7.8+Math.random()*1.9,(Math.random()-.5)*5.3);d.w.set((Math.random()-.5)*18,(Math.random()-.5)*18,(Math.random()-.5)*18)}
function snd(){audio||=new(window.AudioContext||window.webkitAudioContext)();const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(92,t);o.frequency.exponentialRampToValueAtTime(58,t+.08);g.gain.setValueAtTime(.24,t);g.gain.exponentialRampToValueAtTime(.001,t+.095);o.connect(g).connect(audio.destination);o.start();o.stop(t+.1);setTimeout(()=>{const tt=audio.currentTime,buf=audio.createBuffer(1,Math.floor(audio.sampleRate*.055),audio.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=audio.createBufferSource(),bp=audio.createBiquadFilter(),ng=audio.createGain();src.buffer=buf;bp.type='bandpass';bp.frequency.value=1250;ng.gain.setValueAtTime(.16,tt);ng.gain.exponentialRampToValueAtTime(.001,tt+.055);src.connect(bp).connect(ng).connect(audio.destination);src.start();const tri=audio.createOscillator(),tg=audio.createGain();tri.type='triangle';tri.frequency.setValueAtTime(330,tt);tri.frequency.exponentialRampToValueAtTime(145,tt+.07);tg.gain.setValueAtTime(.13,tt);tg.gain.exponentialRampToValueAtTime(.001,tt+.08);tri.connect(tg).connect(audio.destination);tri.start();tri.stop(tt+.08)},170)}
function pop(){if(rolling)return;rolling=true;push.disabled=true;status.textContent='Rolling…';dice.forEach(reset);snd();const s=performance.now();(function a(){const x=performance.now()-s;if(x<150){const k=x/150;dome.scale.set(1-.1*k,1-.27*k,1-.1*k);dome.position.y=.08-.2*k}else{const k=Math.min(1,(x-150)/230),e=1-(1-k)**3;dome.scale.set(.9+.1*e,.73+.27*e,.9+.1*e);dome.position.y=-.12+.2*e}if(x<380)requestAnimationFrame(a);else{dome.scale.set(1,1,1);dome.position.y=.08}})()}
function step(dt){for(const d of dice){if(d.rest===true)continue;if(d.rest==='settling'){d.settleT+=dt;d.m.position.y=T.MathUtils.lerp(d.m.position.y,F,Math.min(1,12.034*dt));const ang=d.m.quaternion.angleTo(d.targetQ);d.m.quaternion.slerp(d.targetQ,Math.min(1,dt*(4.125+Math.max(0,.45-ang)*3.4375)));if(ang<=.009&&d.settleT>=.291){d.m.position.y=F;d.m.quaternion.copy(d.targetQ);d.v.set(0,0,0);d.w.set(0,0,0);d.rest=true}continue}d.t+=dt;d.v.y-=9.8*dt;d.m.position.addScaledVector(d.v,dt);const a=d.w.length()*dt;if(a)d.m.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(d.w.clone().normalize(),a));const rad=Math.hypot(d.m.position.x,d.m.position.z);if(rad>R){const n=new T.Vector3(d.m.position.x,0,d.m.position.z).normalize();d.m.position.x=n.x*R;d.m.position.z=n.z*R;const out=d.v.dot(n);if(out>0)d.v.addScaledVector(n,-1.72*out);d.v.multiplyScalar(.96)}if(d.m.position.y<F){d.m.position.y=F;if(d.v.y<0)d.v.y=-d.v.y*.50;d.v.x*=.915;d.v.z*=.915;d.w.multiplyScalar(.84)}if(d.t>.55&&d.w.length()<5.2){d.w.x+=(Math.random()-.5)*1.15*dt;d.w.z+=(Math.random()-.5)*1.15*dt}if(d.m.position.y<F+.22){const pr=T.MathUtils.clamp((F+.22-d.m.position.y)/.22,0,1);d.w.multiplyScalar(Math.pow(.14,dt*pr))}if(d.t>.38&&d.m.position.y<=F+.035&&Math.abs(d.v.y)<.32&&Math.hypot(d.v.x,d.v.z)<.34&&d.w.length()<1.9){
  d.v.multiplyScalar(.12);d.w.multiplyScalar(.08);
  const ups=[new T.Vector3(0,1,0),new T.Vector3(0,-1,0),new T.Vector3(1,0,0),new T.Vector3(-1,0,0),new T.Vector3(0,0,1),new T.Vector3(0,0,-1)];
  let best=ups[0],score=-99;for(const n of ups){const wn=n.clone().applyQuaternion(d.m.quaternion),sc=wn.y;if(sc>score){score=sc;best=n}}
  const current=best.clone().applyQuaternion(d.m.quaternion),fix=new T.Quaternion().setFromUnitVectors(current,new T.Vector3(0,1,0));
  d.targetQ=fix.multiply(d.m.quaternion.clone());d.settleT=0;d.rest='settling';
 }
 }if(rolling&&dice.every(d=>d.rest===true)){rolling=false;push.disabled=false;status.textContent='Roll complete'}}
function resize(){const side=Math.max(1,Math.round(Math.min(innerWidth,620)));r.setSize(side,side,false);r.domElement.style.width=side+'px';r.domElement.style.height=side+'px';camera.aspect=1;camera.updateProjectionMatrix()}
function loop(now){const dt=Math.min(.024,(now-last)/1000)*1.2;last=now;step(dt);r.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('resize',resize);resize();push.onclick=pop;host.onclick=pop;requestAnimationFrame(loop);