const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(process.argv[2] || 'scripts/scrobble-haptics.js', 'utf8');
function setup({ native = true, fail = false, register = false, custom = false, stored = {}, elements = {}, audioResult } = {}) {
  const calls = [], listeners = {};
  const plugin = {
    impact(options) { calls.push({ method: 'impact', ...options }); return fail ? Promise.reject(Error('unavailable')) : Promise.resolve(); },
    notification(options) { calls.push({ method: 'notification', ...options }); return Promise.resolve(); }
  };
  const rich = { play(options) { calls.push({ method: "play", ...options }); return Promise.resolve(audioResult); }, cancel(options) { calls.push({ method: "cancel", ...options }); return Promise.resolve(); } };
  const cap = { isPluginAvailable: () => custom, isNativePlatform: () => native, Plugins: register ? {} : { Haptics: plugin }, registerPlugin(name) { if(name === "ScrobbleFeedback") return rich; assert.equal(name, 'Haptics'); return plugin; } };
  const ctx = { console: { warn() {} }, localStorage: { getItem: key => stored[key] || null }, window: { Capacitor: cap, addEventListener: (type, fn) => { listeners[type] = fn; } }, document: { getElementById: id => elements[id] || null, addEventListener: (type, fn) => { listeners[type] = fn; } } };
  vm.createContext(ctx); vm.runInContext(source, ctx);
  const button = (id, disabled = false, cpu = false) => ({ id, disabled, getAttribute: () => null, hasAttribute: () => cpu });
  const click = (id, { trusted = true, disabled = false, cpu = false } = {}) => listeners.click({ isTrusted: trusted, target: { closest: () => button(id, disabled, cpu) } });
  return { ctx, calls, listeners, click };
}
(async () => {
  const s = setup();
  s.click('copyInvite'); s.click('shareInvite'); s.click('closeInvite');
  assert(s.calls.every(x => x.style === 'LIGHT'));
  s.click('startFriendGame'); s.click('cpu', { cpu: true });
  assert(s.calls.slice(-2).every(x => x.style === 'MEDIUM'));
  const count = s.calls.length;
  s.click('copyInvite', { disabled: true }); s.click('copyInvite', { trusted: false });
  assert.equal(s.calls.length, count);
  s.listeners.change({ isTrusted: true, target: { matches: () => true } });
  assert.equal(s.calls.at(-1).style, 'LIGHT');
  s.listeners['scrobble:turn-ended']({ detail: { move_type: 'play' } });
  assert.equal(s.calls.at(-1).style, 'LIGHT', 'Word commit must not confirm before score finishes');
  s.ctx.window.ScrobbleHaptics.scoreStart(0, 50);
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.1, 300);
  assert.equal(s.calls.at(-1).style, 'LIGHT');
  const pulses = s.calls.length;
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.11, 310);
  assert.equal(s.calls.length, pulses, 'Adjacent score frames must not spam haptics');
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.5, 1500);
  assert.equal(s.calls.at(-1).style, 'MEDIUM');
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.9, 2700);
  assert.equal(s.calls.at(-1).style, 'HEAVY');
  s.ctx.window.ScrobbleHaptics.scoreEnd(0);
  assert.equal(s.calls.at(-1).type, 'SUCCESS');
  const completed = s.calls.length;
  s.ctx.window.ScrobbleHaptics.scoreEnd(0);
  s.ctx.window.ScrobbleHaptics.scoreStart(0, -10);
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.5, 1000);
  s.ctx.window.ScrobbleHaptics.scoreEnd(0);
  s.ctx.window.ScrobbleHaptics.scoreStart(0, 10);
  s.ctx.window.ScrobbleHaptics.scoreCancel(0);
  s.ctx.window.ScrobbleHaptics.scoreProgress(0, 0.5, 1000);
  s.ctx.window.ScrobbleHaptics.scoreEnd(0);
  assert.equal(s.calls.length, completed, 'Cancelled and decreasing scores must stay silent');
  s.listeners['scrobble:turn-ended']({ detail: { move_type: 'swap' } });
  assert.equal(s.calls.at(-1).style, 'MEDIUM');
  const web = setup({ native: false }); web.click('shareInvite'); assert.equal(web.calls.length, 0);
  const fallback = setup({ register: true }); fallback.click('shareInvite'); assert.equal(fallback.calls.length, 1);
  const rejected = setup({ fail: true }); assert.doesNotThrow(() => rejected.click('copyInvite'));
  await new Promise(resolve => setImmediate(resolve));
  vm.runInContext(source, s.ctx);
  const before = s.calls.length; s.click('copyInvite'); assert.equal(s.calls.length, before + 1);
  const rich = setup({ custom: true });
  const feedback = rich.ctx.window.ScrobbleHaptics;
  feedback.scoreStart(0, 80);
  feedback.scoreProgress(0, .1, 100);
  feedback.scoreProgress(0, .11, 110);
  assert.equal(rich.calls.length, 1);
  feedback.scoreProgress(0, .8, 500);
  feedback.scoreEnd(0);
  assert.deepEqual(rich.calls.map(x => x.kind), ['score', 'score', 'finish']);
  assert.equal(rich.calls[2].gain, 80);
  assert(rich.calls.every(x => x.sound && x.haptics));
  feedback.scoreStart(1, 20); feedback.scoreProgress(1, .2, 600);
  rich.ctx.document.hidden = true; rich.listeners.visibilitychange();
  assert.equal(rich.calls.at(-1).method, 'cancel');
  const afterCancel = rich.calls.length; feedback.scoreEnd(1);
  assert.equal(rich.calls.length, afterCancel);
  const faster = setup({ custom: true });
  faster.ctx.window.ScrobbleHaptics.scoreStart(0, 30);
  faster.ctx.window.ScrobbleHaptics.scoreProgress(0, 0, 0);
  faster.ctx.window.ScrobbleHaptics.scoreProgress(0, 0, 199);
  assert.equal(faster.calls.length, 1);
  faster.ctx.window.ScrobbleHaptics.scoreProgress(0, 0, 200);
  assert.equal(faster.calls.length, 2, 'Pulse cadence must increase exactly 30%');
  const muted = setup({ custom: true, stored: { 'scrobble-feedback-sound': 'off', 'scrobble-feedback-haptics': 'off' } });
  muted.ctx.window.ScrobbleHaptics.scoreStart(0, 30);
  muted.ctx.window.ScrobbleHaptics.scoreProgress(0, .5, 500);
  assert.equal(muted.calls.at(-1).sound, false); assert.equal(muted.calls.at(-1).haptics, false);
  for (const result of [{ audioPlayed: true }, { audioPlayed: false, audioError: 'Missing asset' }]) {
    let handler;
    const test = { disabled: false, addEventListener: (_, fn) => { handler = fn; } };
    const status = { textContent: '' };
    const tested = setup({ custom: true, audioResult: result, elements: { 'feedback-test': test, 'feedback-test-status': status } });
    await handler();
    assert.equal(test.disabled, false);
    assert.equal(tested.calls.at(-1).sound, true);
    assert.equal(tested.calls.at(-1).haptics, false);
    assert(status.textContent.includes(result.audioPlayed ? 'Test chime played' : 'Missing asset'));
  }
  console.log('PASS: native patterns, score crescendo and payoff, frame throttling, background cancellation, mute settings, preset fallback, and safe plugin failure.');
})().catch(error => { console.error(error); process.exitCode = 1; });
